
pager = "less -R"

[git]
  autoCommit = false
  autoPush = false
  autoAdd = true

[diff]
  exclude = ["externals", "scripts"]
  pager = "delta"

{{- if lookPath "nvim" }}
[merge]
  command = "nvim"
  args = ["-d"]
{{- end }}

