#!/usr/bin/env bash
# For a more advanced configuration example see:
# https://github.com/FelixKratz/SketchyBar/discussions/47#discussioncomment-2027233
# vi: ft=sh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

source "$HOME/.config/sketchybar/styles.sh"

bar=(
  height=40
  blur_radius=20
  display=main   
  position=top   
  margin=$BAR_MARGIN  
  y_offset=$BAR_Y_OFFSET  
  corner_radius=$BAR_CORNER_RADIUS   
  padding_left="$H_PADDING"  
  padding_right="$H_PADDING" 
  color="$BAR_BACKGROUND_COLOR" 
  font_smoothing=true
)

sketchybar --bar "${bar[@]}"


##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items
#
default=(
  updates=when_shown           
  drawing=on              
  icon.font="$ICON_FONT"  
  icon.color=$COLOR_WHITE 
  label.font="$LABEL_FONT"
  label.color=$COLOR_WHITE
  label.padding_left=4    
  label.padding_right=4   
  icon.padding_left=4     
  icon.padding_right=4
)

sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces


source "$ITEM_DIR/apple.sh"

space_styles() {
  space_index=$1
  styles=(
    associated_space=$space_index                   
    icon=${SPACE_ICONS[$space_index-1]}                         
    icon.highlight_color="$PRIMARY_COLOR"          
    icon.padding_left="$ICON_H_PADDING"            
    icon.padding_right="$ICON_H_PADDING"           
    background.padding_left=0
    background.padding_right=0
    background.color=$PRIMARY_COLOR_LIGHT          
    background.corner_radius=5
    background.height=40
    label.drawing=off                              
    script="$PLUGIN_DIR/space.sh"                  
  )
  echo "${styles[@]}"
}

SPACE_ICONS=("" "󰊯" "󰒱" "󰃭" "󰝚")


##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

media=(
  script="$PLUGIN_DIR/media.sh"
  updates=on
)

# Uncomment when event media_change is released
# sketchybar --add item media center                               \
#           --set media "${media[@]}"                               \
#           --subscribe media media_change                     \


sketchybar --add item space_separator left                            \
           --set space_separator icon=""                               \
                                 background.padding_left=5           \
                                 background.padding_right=5          \
                                 label.drawing=off                    \
           --add item window_title left                               \
           --set window_title    script="$PLUGIN_DIR/window_title.sh" \
                                 icon.drawing=off                     \
           --subscribe window_title front_app_switched

for i in "${!SPACE_ICONS[@]}"
do
  index=$(($i+1))
  styles=$(space_styles $index)
  sketchybar --add space space.$index left  --set space.$index $styles
done

##### Adding Right Items #####
sketchybar --add item clock right                        \
           --set clock   update_freq=10                  \
                         script="$PLUGIN_DIR/clock.sh"   \
           --add item wifi right                        \
           --set wifi script="$PLUGIN_DIR/wifi.sh"   \
                      update_freq=10                  \
           --add item battery right                      \
           --set battery script="$PLUGIN_DIR/battery.sh" \
                         update_freq=10                  \
           --subscribe battery system_woke

##### Finalizing Setup #####
sketchybar --update

echo "sketchybar configuration loaded.."
