#!/usr/bin/env sh

## COLORS
BAR_BACKGROUND_COLOR=0xff1E1E2E
PRIMARY_COLOR=0xffCBA6F7
PRIMARY_COLOR_LIGHT=0x44CBA6F7
COLOR_WHITE=0xffffffff

### SPACING
H_PADDING=600
ICON_H_PADDING=10

## FONTS
ICON_FONT="JetBrainsMono Nerd Font:Bold:18"
