#!/usr/bin/env sh

### Fonts ###
icon_font="FiraCode Nerd Font Mono"
text_font="JetBrains Mono"

### Colors ###

## Catppuccin ##

# Mocha
# white='7b819d' # overlay1
white='9399b2' # overlay2
black='1F1E2F'
green='a6e3a1'
purple='b4befe'
blue='89b4fa'
red='eba0ac' 

### Settings ###
spacebar -m config position                    top
spacebar -m config display                     main
spacebar -m config height                      32
spacebar -m config title                       on
spacebar -m config padding_left                15
spacebar -m config padding_right               15
spacebar -m config spacing_left                25
spacebar -m config spacing_right               30
spacebar -m config text_font                   "$text_font:Regular:12"
spacebar -m config icon_font                   "$icon_font:Regular:20"
spacebar -m config background_color            0xff$black
spacebar -m config foreground_color            0xff$white

# Do not disturb
spacebar -m config dnd_icon_color              0xff$purple
spacebar -m config dnd_icon                    

# Spaces
spacebar -m config spaces                      on
spacebar -m config space_icon                  "" 
spacebar -m config space_icon_color            0xff$red
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0
spacebar -m config space_icon_strip            "" "聆" ""
spacebar -m config spaces_for_all_displays     off

# Power
spacebar -m config power                       on
spacebar -m config power_icon_strip             ﴞ 
spacebar -m config power_icon_color            0xff$green
spacebar -m config battery_icon_color          0xff$white

# Clock
spacebar -m config clock                       on
spacebar -m config clock_icon                   
spacebar -m config clock_format                '%I:%M %p - %d.%m'
spacebar -m config clock_icon_color            0xff$purple
# spacebar -m config right_shell                 off
# spacebar -m config right_shell_icon            ﬉
# spacebar -m config right_shell_icon_color      0xff$white

echo "spacebar configuration loaded.."
