gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  showFileTree: true
  nerdFontsVersion: "3"
  showCommandLog: true
  commandLogSize: 20
  border: "rounded"
git:
  branchLogCmd: "git log --graph --color=always --decorate --oneline --all"
  paging:
    colorArg: always
    useConfig: true
