gui:
  theme:
    selectedLineBgColor:
      - reverse
  showFileTree: true
  nerdFontsVersion: "3"
  showCommandLog: true
  commandLogSize: 20
  border: "rounded"
git:
  branchLogCmd: "git log --graph --color=always --decorate --oneline --all"
  paging:
    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=on --tab-width=2
os:
  editPreset: nvim
