gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  showFileTree: true
  showIcons: true
# delta doesn't work well
# git:
#   paging:
#     colorArg: always
#     useConfig: true
