[theme]
rosewater = "#F5E0DC"
flamingo = "#F2CDCD"
pink = "#F48FB1"
mauve = "#D4BFFF"
red = "#F02E6E"
maroon = "#F48FB1"
peach = "#F2B482"
yellow = "#FFE6B3"
green = "#A1EFD3"
teal = "#63F2F1"
sky = "#ABF8F7"
sapphire = "#91DDFF"
blue = "#78A8FF"
lavender = "#7676FF"
white = "#CBE3E7"

# Text
text = "#CBE3E7"
subtext1 = "#8A889D"
subtext0 = "#8A889D"
overlay2 = "#585273"
overlay1 = "#585273"
overlay0 = "#3E3859"
surface2 = "#3E3859"
surface1 = "#2F2A47"
surface0 = "#1E1C31"

# Background
base = "#1E1C31"
mantle = "#100E23"
crust = "#100E23"
