dependencies = ["gh", "jira", "nobob", "xs"]


[[tab]]
  name = " Today"
  modules = ["day-progress", "Weather", "Calendar", "todos"]

[[tab]]
  name = " GitHub"
  modules = ["pr-status", "prs"]

[[tab]]
  name = "󱣘 Containers"
  modules = ["nobob-swapped", "nobob-doctor", "colima"]

[[tab]]
  name = "󰌃 Jira"
  modules = ["my-issues", "open-issues"]


[[module]]
  name = "day-progress"
  title = "Day Progress"
  exec = """
  day-progress --start "9:30AM" --end "5:30PM"
  """
  width = 9999

[[module]]
  name = "Weather"
  title = "☀ Weather"
  exec = "curl --silent wttr.in/montreal?0AQ"
  width = 35

[[module]]
  name = "Calendar"
  exec = "bash -c cal"

[[module]]
  name = "todos"
  exec = "todo view"
  dir = "/Users/evan.godon/code/monocle"

[[module]]
  name = "todoist"
  exec = "./todoist.ts"

[[module]]
  name = "agenda-today"
  title = "Today's Agenda"
  exec = """
  gcalcli agenda today tomorrow
  """
  width = 65

[[module]]
  name = "default-todo"
  title = "Todo List"
  exec = "todo --file ~/.todo.md view"
  width = 80


# JIRA
[[module]]
  name = "my-issues"
  title = "Tickets assigned to me"
  exec = """
  jira issue list -a$(jira me) --status "~Closed"  --status "~Prod Awaiting Verification" --plain --columns key,assignee,status --paginate 20 | cat
  """

[[module]]
  name = "open-issues"
  title = "Open tickets"
  exec = "jira sprint list --current --plain --status Open | cat"


[[module]]
  name = "colima"
  title = "Colima Status"
  exec = "colima status --extended"

# NOBOB
[[module]]
  name = "nobob-swapped"
  title = "Nobob Swapped"
  exec = "nobob swapped"

[[module]]
  name = "nobob-doctor"
  title = "Nobob Doctor"
  exec = "xs nobob doctor"
  Dir = "/Users/evan.godon/code/nobob"

# GITHUB
[[module]]
  name = "pr-status"
  title = "PR Status"
  exec = "gh pr status"
  dir = "."

[[module]]
  name = "prs"
  title = "My PRs"
  exec = "gh pr list --author @me --limit 5"
  dir = "."

[settings]
  primary-color = "#fab387"
