dependencies = ["gh", "jira", "nobob", "xs"]


[[tab]]
  name = " Today"
  modules = ["day-progress", "Weather", "Calendar", "todoist"]

[[tab]]
  name = " GitHub"
  modules = ["pr-status", "prs"]

[[tab]]
  name = "󱣘 nobob"
  modules = ["nobob-swapped", "nobob-doctor"]

[[tab]]
  name = "󰌃 Jira"
  modules = ["my-issues"]


[[module]]
  name = "day-progress"
  title = "Day Progress"
  exec = "day-progress"
  width = 120

[[module]]
  name = "Weather"
  title = "☀ Weather"
  exec = "curl --silent wttr.in/montreal?0AQ"
  width = 35

[[module]]
  name = "Calendar"
  exec = "bash -c cal"

[[module]]
  name = "todoist"
  exec = "./todoist.ts"

[[module]]
  name = "agenda-today"
  title = "Today's Agenda"
  exec = """
  gcalcli agenda today tomorrow
  """
  width = 65

[[module]]
  name = "default-todo"
  title = "Todo List"
  exec = "todo --file ~/.todo.md view"
  width = 80


# JIRA
[[module]]
  name = "issues"
  title = "Jira"
  exec = "jira issue list --plain --columns key,assignee,status --paginate 20"
  width = 100

[[module]]
  name = "my-issues"
  title = "Assigned to me"
  exec = "jira issue list -a$(jira me) --plain"
  width = 130

# NOBOB
[[module]]
  name = "nobob-swapped"
  title = "Nobob Swapped"
  exec = "nobob swapped"

[[module]]
  name = "nobob-doctor"
  title = "Nobob doctor"
  exec = "xs nobob doctor"
  Dir = "/Users/evan.godon/code/nobob"

# GITHUB
[[module]]
  name = "pr-status"
  title = "PR Status"
  exec = "gh pr status"
  dir = "."

[[module]]
  name = "prs"
  title = "PRs"
  exec = "gh pr list --limit 20"
  dir = "."
